#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run format
npm run format
if [ $? -ne 0 ]; then
  echo "❌ Format failed. Commit aborted."
  exit 1
fi

# Run lint
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ Lint failed. Commit aborted."
  exit 1
fi

# Run analyze
npm run analyze
if [ $? -ne 0 ]; then
  echo "❌ Analyze failed. Commit aborted."
  exit 1
fi

echo "✅ All checks passed!"
